<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <ProjectReference Include="..\Platform.Application\Platform.Application.csproj" />
    <ProjectReference Include="..\Platform.Infrastructure\Platform.Infrastructure.csproj" />
    <ProjectReference Include="..\Platform.Contracts\Platform.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Platform.Worker-3b2fa0dc-19ee-4a42-a78d-5aa97141e74e</UserSecretsId>
  </PropertyGroup>
</Project>
