SET NOCOUNT ON;
GO

DECLARE @Now datetime2 = SYSUTCDATETIME();

MERGE dbo.AiPromptTemplate AS target
USING (
    VALUES
    (
        CAST('40000000-0000-0000-0000-000000000001' AS uniqueidentifier),
        NULL,
        N'PRODUCT_LONGDESC_GENERATE_V1',
        N'Product Long Description Generate',
        N'ProductTranslation',
        N'LongDescription',
        N'Generate',
        NULL,
        NULL,
        N'Write a clear, commercially useful product long description based on the supplied product data, attributes, brand, and category context. Focus on benefits, key features, likely use cases, and important differentiators. Do not invent specifications that are not present in the input. Return plain text or HTML-lite content suitable for e-commerce.',
        N'You are generating structured e-commerce product copy for a backoffice editor. Be specific, factual, concise, and useful. Avoid hype, unverifiable claims, and filler.',
        N'Text',
        NULL,
        CAST(0.4 AS decimal(4,3)),
        900,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000002' AS uniqueidentifier),
        NULL,
        N'PRODUCT_SHORTDESC_GENERATE_V1',
        N'Product Short Description Generate',
        N'ProductTranslation',
        N'ShortDescription',
        N'Generate',
        NULL,
        NULL,
        N'Write a short product description for use on listing pages and summary blocks. Keep it concise, informative, and aligned with the supplied catalog data. Do not invent facts.',
        N'Produce compact e-commerce summary copy. Prioritize clarity over style.',
        N'Text',
        NULL,
        CAST(0.3 AS decimal(4,3)),
        220,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000003' AS uniqueidentifier),
        NULL,
        N'PRODUCT_SEOTITLE_GENERATE_V1',
        N'Product SEO Title Generate',
        N'ProductTranslation',
        N'SeoTitle',
        N'Generate',
        NULL,
        NULL,
        N'Generate an SEO title for a product page based on the supplied product information. Keep it concise, relevant, and readable. Prefer strong keyword relevance over brand fluff.',
        N'Output a single SEO-friendly title. Avoid clickbait and unnecessary punctuation.',
        N'Text',
        NULL,
        CAST(0.2 AS decimal(4,3)),
        80,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000004' AS uniqueidentifier),
        NULL,
        N'PRODUCT_SEODESC_GENERATE_V1',
        N'Product SEO Description Generate',
        N'ProductTranslation',
        N'SeoDescription',
        N'Generate',
        NULL,
        NULL,
        N'Generate a meta description for a product page based on the supplied product information. Keep it natural, concise, and useful for search snippets. Do not include fabricated claims.',
        N'Output a single meta description, typically around 140-160 characters when possible.',
        N'Text',
        NULL,
        CAST(0.2 AS decimal(4,3)),
        120,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000005' AS uniqueidentifier),
        NULL,
        N'PRODUCT_NAME_TRANSLATE_V1',
        N'Product Name Translate',
        N'ProductTranslation',
        N'Name',
        N'Translate',
        NULL,
        NULL,
        N'Translate the supplied product name into the requested target language. Preserve brand names, measurements, model numbers, and product-identifying terminology unless local language conventions require otherwise.',
        N'Produce a natural product name translation suitable for e-commerce search and display. Keep it compact.',
        N'Text',
        NULL,
        CAST(0.1 AS decimal(4,3)),
        80,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000006' AS uniqueidentifier),
        NULL,
        N'PRODUCT_DESC_TRANSLATE_V1',
        N'Product Description Translate',
        N'ProductTranslation',
        N'LongDescription',
        N'Translate',
        NULL,
        NULL,
        N'Translate the supplied product description into the requested target language. Preserve factual meaning, structure, technical terminology, measurements, and branded terms. Do not add new claims or omit important product details.',
        N'Produce natural e-commerce translation with accurate terminology and stable meaning.',
        N'Text',
        NULL,
        CAST(0.1 AS decimal(4,3)),
        1000,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000007' AS uniqueidentifier),
        NULL,
        N'PRODUCT_SHORTDESC_REWRITE_V1',
        N'Product Short Description Rewrite',
        N'ProductTranslation',
        N'ShortDescription',
        N'Rewrite',
        NULL,
        NULL,
        N'Rewrite the supplied short product description to improve clarity, structure, and readability while preserving meaning and factual accuracy. Keep it concise and suitable for e-commerce.',
        N'Preserve the original meaning. Remove fluff and awkward phrasing.',
        N'Text',
        NULL,
        CAST(0.3 AS decimal(4,3)),
        220,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000008' AS uniqueidentifier),
        NULL,
        N'PRODUCT_LONGDESC_REWRITE_V1',
        N'Product Long Description Rewrite',
        N'ProductTranslation',
        N'LongDescription',
        N'Rewrite',
        NULL,
        NULL,
        N'Rewrite the supplied long product description to improve readability, structure, and commercial usefulness while preserving the underlying facts. Keep important features and use cases intact. Do not invent new information.',
        N'Act as an experienced e-commerce editor. Make the text clearer and more useful without changing the product facts.',
        N'Text',
        NULL,
        CAST(0.3 AS decimal(4,3)),
        1000,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000009' AS uniqueidentifier),
        NULL,
        N'PRODUCT_ATTRIBUTES_SUMMARIZE_V1',
        N'Product Attributes Summarize',
        N'ProductTranslation',
        N'ShortDescription',
        N'Summarize',
        NULL,
        NULL,
        N'Create a short summary from the supplied structured product facts and attributes. Focus on the most important purchase-driving information. Do not fabricate missing details.',
        N'Produce a compact summary based on structured product data.',
        N'Text',
        NULL,
        CAST(0.2 AS decimal(4,3)),
        200,
        1,
        @Now,
        @Now
    ),
    (
        CAST('40000000-0000-0000-0000-000000000010' AS uniqueidentifier),
        NULL,
        N'PRODUCT_SEODESC_TRANSLATE_V1',
        N'Product SEO Description Translate',
        N'ProductTranslation',
        N'SeoDescription',
        N'Translate',
        NULL,
        NULL,
        N'Translate the supplied SEO meta description into the requested target language while preserving search intent, factual meaning, and compact length.',
        N'Produce a concise translated meta description suitable for search snippets.',
        N'Text',
        NULL,
        CAST(0.1 AS decimal(4,3)),
        140,
        1,
        @Now,
        @Now
    )
) AS source (
    Id,
    TenantId,
    Code,
    Name,
    EntityType,
    FieldKey,
    Capability,
    CultureCode,
    MarketId,
    PromptText,
    SystemInstruction,
    OutputFormat,
    ModelName,
    Temperature,
    MaxTokens,
    IsActive,
    CreatedAtUtc,
    UpdatedAtUtc
)
ON target.TenantId IS NULL
   AND target.Code = source.Code
WHEN MATCHED THEN
    UPDATE SET
        target.Name = source.Name,
        target.EntityType = source.EntityType,
        target.FieldKey = source.FieldKey,
        target.Capability = source.Capability,
        target.CultureCode = source.CultureCode,
        target.MarketId = source.MarketId,
        target.PromptText = source.PromptText,
        target.SystemInstruction = source.SystemInstruction,
        target.OutputFormat = source.OutputFormat,
        target.ModelName = source.ModelName,
        target.Temperature = source.Temperature,
        target.MaxTokens = source.MaxTokens,
        target.IsActive = source.IsActive,
        target.UpdatedAtUtc = source.UpdatedAtUtc
WHEN NOT MATCHED THEN
    INSERT (
        Id,
        TenantId,
        Code,
        Name,
        EntityType,
        FieldKey,
        Capability,
        CultureCode,
        MarketId,
        PromptText,
        SystemInstruction,
        OutputFormat,
        ModelName,
        Temperature,
        MaxTokens,
        IsActive,
        CreatedAtUtc,
        UpdatedAtUtc
    )
    VALUES (
        source.Id,
        source.TenantId,
        source.Code,
        source.Name,
        source.EntityType,
        source.FieldKey,
        source.Capability,
        source.CultureCode,
        source.MarketId,
        source.PromptText,
        source.SystemInstruction,
        source.OutputFormat,
        source.ModelName,
        source.Temperature,
        source.MaxTokens,
        source.IsActive,
        source.CreatedAtUtc,
        source.UpdatedAtUtc
    );
GO
